apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: pod
    command: ['sh','-c','sleep 4800']
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 65534
      runAsUser: 65534
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
