apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-deploy
  name: busybox-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: busybox-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: busybox-deploy
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ['sh','-c','sleep 4800']
        resources: {}
        
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65534
          runAsUser: 65534
      dnsPolicy: ClusterFirst
      restartPolicy: Always

