apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-whereabouts-conf
spec:
  containers:
  - image: busybox
    name: pod
    command: ['sh','-c','sleep 4800']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
