apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busybox-deploy
  name: busybox-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: busybox-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox-deploy
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan-whereabouts-conf
    spec:
      containers:
      - image: busybox
        name: pod
        command: ['sh','-c','sleep 4800']
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
