apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busybox-deploy2
  name: busybox-deploy2
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: busybox-deploy2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox-deploy2
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan-whereabouts-conf
    spec:
      containers:
      - image: busybox
        name: pod
        command: ['sh','-c','sleep 4800']
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: workerid
                operator: In
                values:
                - worker2
