#! The FQDN for accessing Harbor admin UI and Registry service.
hostname: harbor.h2o-2-16768.h2o.vmware.com

#! The network port of the Envoy service in Contour or other Ingress Controller.
port:
  https: 443

#! Do not change tlsSecretLabels. It is required for TKG  integration to work.
tlsCertificate:
  tlsSecretLabels: {"managed-by": "vmware-vRegistry"}
 
#! [Required] The initial password for the Harbor admin account. This is applied
#! only during installation. Future updates to the password should be done
#! using the Harbor UI or API.
harborAdminPassword: VMware1!
 
#! [Required] The secret key used for encryption. Must be a string of 16 chars.
secretKey: 0123456789ABCDEF
 
database:
  #! [Required] The initial password of the postgres database.
  password: change-it
 
core:
  replicas: 1
  #! [Required] Secret is used when core server communicates with other components.
  secret: change-it
  #! [Required] The XSRF key. Must be a string of 32 chars.
  xsrfKey: 0123456789ABCDEF0123456789ABCDEF
jobservice:
  replicas: 1
  #! [Required] Secret is used when job service communicates with other components.
  secret: change-it
registry:
  replicas: 1
  #! [Required] Secret is used to secure the upload state from client
  #! and registry storage backend.
  #! See: https://github.com/docker/distribution/blob/master/docs/configuration.md#http
  secret: change-it
notary:
  #! Notary is unsupported on vSphere Supervisor Clusters.
  enabled: false
 
#! Specify another StorageClass in the "storageClass" or set "existingClaim"
#! if you have already existing persistent volumes to use
persistence:
  persistentVolumeClaim:
    registry:
      #! Specify the "storageClass" used to provision the volume.
      #! Please use what is available in your environment.
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 10Gi
    jobservice:
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
 
#! The metrics used by core, registry and exporter
metrics:
  enabled: true
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001

#! Note: IPv6 is not supported on Supervisor. Including it will cause harbor-portal to fail.
network:
  ipFamilies: ["IPv4"]
