apiVersion: run.tanzu.vmware.com/v1alpha1      #TKGS API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: tkc-velero
  namespace: velero
spec:
  distribution:
    version: v1.19                            #Resolves to the latest v1.18 image
  settings:
    storage:
            #      classes: [pacific-gold-storage-policy]
      defaultClass: k8s-storage
                          #Resolves to the latest v1.18 image
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-small                 #vmclass for control plane nodes
      storageClass: k8s-storage
    workers:
      count: 1                                 #number of worker nodes
      class: best-effort-small                 #vmclass for worker nodes
      storageClass: k8s-storage
