
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: myns-mytkc-beta
  namespace: myns # !!! IMPORTANT bounds to workload network in supervisor
spec:
  topology:
    class: tanzukubernetescluster
    version: v1.23.8---vmware.2-tkg.2-zshippable
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 2
    variables:
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: vc01cl01-t0compute
      - name: defaultStorageClass
        value: vc01cl01-t0compute
