apiVersion: run.tanzu.vmware.com/v1alpha1      #TKGS API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: tkc1
  namespace: ns1     # !!! IMPORTANT bounds to workload network in supervisor
spec:
  distribution:
    version: v1.18                             #Resolves to the latest v1.18 image
  settings:
    storage:
    # classes: [pacific-gold-storage-policy]
      defaultClass: pacific-gold-storage-policy
                          
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-small                 #vmclass for control plane nodes
      storageClass: pacific-gold-storage-policy
    workers:
      count: 3                                 #number of worker nodes
      class: best-effort-small                 #vmclass for worker nodes
      storageClass: pacific-gold-storage-policy
