
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echoserver
imagePullSecrets:
- name: harbor-registry-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echoserver
  name: echoserver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echoserver
      annotations:
        fluentbit.io/parser: echoserver
    spec:
      containers:
      - image: echoserver:1.4
        name: echoserver-app
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources: {}
      serviceAccount: echoserver
      serviceAccountName: echoserver
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-app-service
spec:
  type: LoadBalancer
  #type: ClusterIP
  externalTrafficPolicy: Local
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
