#k create secret docker-registry harbor-registry-secret --docker-server=10.213.70.67 --docker-username=kminseok@vsphere.local --docker-password=VMware1! -n kminseok -o yaml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4yMTMuNzAuNjciOnsidXNlcm5hbWUiOiJrbWluc2Vva0B2c3BoZXJlLmxvY2FsIiwicGFzc3dvcmQiOiJWTXdhcmUxISIsImF1dGgiOiJhMjFwYm5ObGIydEFkbk53YUdWeVpTNXNiMk5oYkRwV1RYZGhjbVV4SVE9PSJ9fX0=
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: kminseok
type: kubernetes.io/dockerconfigjson
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: echoserver
imagePullSecrets:
- name: harbor-registry-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echoserver
  name: echoserver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echoserver
      annotations:
        fluentbit.io/parser: echoserver
    spec:
      containers:
      - image: 10.213.70.67/kminseok/echoserver:1.4
        name: echoserver-app
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources: {}
      serviceAccount: echoserver
      serviceAccountName: echoserver
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-app-service
spec:
  type: LoadBalancer
  #type: ClusterIP
  externalTrafficPolicy: Local
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
