apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd
  name: httpd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd
      annotations:
        fluentbit.io/parser: httpd
    spec:
#imagePullSecrets:
#      - name: harbor-registry-secret
      containers:
      - image: httpd
        name: httpd-app
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources: {}
      serviceAccount: httpd
      serviceAccountName: httpd
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-app-service
spec:
  type: LoadBalancer
  #type: ClusterIP
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
