

# kubectl create secret docker-registry harbor-registry-secret --docker-server=10.213.70.67 --docker-username=kminseok@vsphere.local --docker-password=VMware1! -n kminseok -o yaml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4yMTMuNzAuNjciOnsidXNlcm5hbWUiOiJrbWluc2Vva0B2c3BoZXJlLmxvY2FsIiwicGFzc3dvcmQiOiJWTXdhcmUxISIsImF1dGgiOiJhMjFwYm5ObGIydEFkbk53YUdWeVpTNXNiMk5oYkRwV1RYZGhjbVV4SVE9PSJ9fX0=
kind: Secret
metadata:
  name: harbor-registry-secret
type: kubernetes.io/dockerconfigjson
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
imagePullSecrets:
- name: harbor-registry-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
      annotations:
        fluentbit.io/parser: nginx
    spec:
#imagePullSecrets:
#      - name: harbor-registry-secret
      containers:
      #- image: infra-harbor2.lab.pcfdemo.net/library/nginx:latest
      - image: nginx
        name: nginx-app
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources: {}
      serviceAccount: nginx
      serviceAccountName: nginx
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  type: LoadBalancer
  #type: ClusterIP
  externalTrafficPolicy: Local
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
