
## cluster resource. it works regardless of namespace

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
spec:
  maxUnavailable: "20%"
  #minAvailable: 1
  selector:
    matchLabels:
      app: nginx