apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-web-config
  annotations:
    kapp.k14s.io/identity: v1;tanzu-system-monitoring//ConfigMap/prometheus-server;v1
  labels:
    app: prometheus
    component: server
data:
  prometheus_web_config.yml: |
    ## https://github.com/prometheus/prometheus/blob/release-2.47/documentation/examples/web-config.yml
    # Usernames and passwords required to connect to Prometheus.
    # Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
    # htpasswd -nBC 10 "" | tr -d ':\n'
    # VMware1! $2y$10$uC5K6atkxsgtobH4QQQrLeldPynEZprlHuuXPu/vY7O0y9pzOOPs2
    ## test: $2b$12$hNf2lSsxfm0.i4a.1kVpSOVyBCfIB51VRjgBUyv6kdnyTlgWj81Ay
    basic_auth_users:
      admin: $2y$10$uC5K6atkxsgtobH4QQQrLeldPynEZprlHuuXPu/vY7O0y9pzOOPs2