alertmanager:
  deployment:
    replicas: 0
#   pvc:
#     accessMode: ReadWriteOnce
#     storage: 2Gi
#   service:
#     port: 80
#     targetPort: 9093
#     type: ClusterIP
# cadvisor:
#   daemonset:
#     updatestrategy: RollingUpdate
# ingress:
#   alertmanager_prefix: /alertmanager/
#   alertmanagerServicePort: 80
#   enabled: false
#   prometheus_prefix: /
#   prometheusServicePort: 80
#   virtual_host_fqdn: prometheus.system.tanzu
# kube_state_metrics:
#   deployment:
#     replicas: 1
#   service:
#     port: 80
#     targetPort: 8080
#     telemetryPort: 81
#     telemetryTargetPort: 8081
#     type: ClusterIP
# namespace: tanzu-system-monitoring
# node_exporter:
#   daemonset:
#     hostNetwork: false
#     updatestrategy: RollingUpdate
#   service:
#     port: 9100
#     targetPort: 9100
#     type: ClusterIP
# prometheus:
#   deployment:
#     configmapReload:
#       containers:
#         args: webhook-url=http://127.0.0.1:9090/-/reload
#     containers:
#       args: prometheus storage retention time = 42d
#     replicas: 1
#   pvc:
#     accessMode: ReadWriteOnce
#     storage: 150Gi
#   service:
#     port: 80
#     targetPort: 9090
#     type: ClusterIP
pushgateway:
  deployment:
    replicas: 0
#   service:
#     port: 9091
#     targetPort: 9091
#     type: ClusterIP
