apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx3
  name: nginx3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx3
      annotations:
        fluentbit.io/parser: nginx3
    spec:
#imagePullSecrets:
#      - name: harbor-registry-secret
      containers:
      - image: nginx
        #- image: infra-harbor.lab.pcfdemo.net/library/nginx3:latest
        name: nginx3-app
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources: {}
      serviceAccount: nginx3
      serviceAccountName: nginx3
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx3-app-service
spec:
  type: LoadBalancer
  #type: ClusterIP
  selector:
    app: nginx3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
