apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpproxy-testcom
  namespace: test-ingress
spec:
  virtualhost:
    fqdn: foo2.pcfdemo.net
    tls:
      secretName: default/tls-testcom
  routes:
    - services:
        - name: s1
          port: 80
