apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
   app: redis-server
spec:
  storageClassName: k8s-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
