kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-leader-pvc
spec:
  accessModes:
    - ReadWriteOnce
      #  storageClassName: k8s-storage
  resources:
    requests:
      storage: 2Gi
