apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-space-rolebinding
  namespace: org1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-space-edit-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sso:user1@vsphere.local
