#https://cert-manager.io/docs/usage/certificate/
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-testlab.pcfdemo.net
spec:
  # Secret names are always required.
  secretName: nginx-tls
  renewBefore: 360h # 15d
  subject:
    organizations:
      - homelab
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: lab.pcfdemo.net
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - nginx-test.lab.pcfdemo.net
  ipAddresses:
    - 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
