apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yelb-redis-server-pvc
  labels:
   app: redis-server
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  #- ReadWriteMany
  resources:
    requests:
      storage: 3Gi
