apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgBAqTsfYLzgpwTUFXFwPJn7iG9xZYgBncHn/YTh/ZcMnB0r9BFdUMPNyfhdSbIZkpvf4cr5cAD6nN1Tg9cCtn0sge8kF/jsYaPfdEdonyvFmnsqo8Fz9NWkNWsTxplNS/AOvLZuc6Jx9p2uMsziu8iscFd+otWdiuy+MAsdQwViattuoUY4FGN5umxQxUOiRtk5m+KOhJNEmxAUZaL4bqhv0LnqCzbBYXus648PTbloN7ZgvH1ZHWXI1Vd2rlhSgpXncCVXjigFbSWfI99Au2VQCrqUYFQ8SYYBMzXrIfAPFD3KxM59R5zv1rR/9JSHK5lsNCUveipaYodFuiTBcyBz4vUnmclAnp0s7JofV4bA7TbAv3UzMltj1WBve8BulKhTpR4VsQmQ1tfEpPs7r8WCw8t4qoeMBSRJTL0iWzz/MLiDauZsHDSyBMBW3NyfW1MtTQ5sXNCzGb8XYbp0GkNzCN5Wgx7HViMxIHyQgj1j7YB9zcutjkucOuu1InLGZmcmcgy3K39u3I4t3eHuKoYRIRB+RUe/SAsndpkhKpEnoVG4EPHS3G/yfPtvx88vqt/hF0mMHPAu1KZg+bmcotHrNXC9T85K1q/uA4fZlW5jycCHNSVchvDBP+8w4LvTxLMrdmjBVyS7ExjWsmrGVy1n4imZOl7yFUM/VlSFL05pRmW+u+75VHycn7uT/BbZLDzyl+U=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

