apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - image: 10.90.12.130/kmin-test/praqma/network-multitool:1
    imagePullPolicy: Always
    name: jumpbox
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "1Gi"
